### ISSUE TITLE
Feature idea: A table of which FreeBSD version and architecture has a given package.

### ISSUE THREAD

**Issue by debdrup** [FreshPorts/freshports#142]
The idea is to use packagesite.yaml from https://pkg.freebsd.org/$ABI/latest/packagesite.txz to extract the package category/name to match on, and the version, so that a table can be displayed can give an idea of the following:
- When the latest package was made available
- What architecture(s) the package is available on
- What major version(s) the package is available on

I imagine for layout it would be something like this:
| Arch/Ver | 11 | 12 | 13 | 
|----------------------|----|----|----|
| amd64                     |  date  |  date  | date |
| i386                 |  date  |  date  |  date  |
|  aarch64                |   date |  date  |  date  |
|  ppc64                |   date |  N/A  |  date  |

Et cetera ad nauseum, you get the idea.

Date would of course be from the yaml file, N/A would be used whenever a package is:
- Not built (for whatever reason)
- Ignored (restricted, et cetera)

**Comment by dlangille** [comment]
Things to know:

- How do we know what archs are available?
- How do we know what versions?

**Comment by dlangille** [comment]
This is what I got while playing around today on the `mydev` server:

$ mkdir -p ~/tmp/FreshPorts/pkg.freebsd.org/FreeBSD:12:amd64/latest
$ cd ~/tmp/FreshPorts/pkg.freebsd.org/FreeBSD:12:amd64/latest
$ fetch https://pkg.freebsd.org/FreeBSD:12:amd64/latest/packagesite.txz
$ unxz packagesite.txz
$ ls -l
total 18456
-rw-r--r--  1 dan  dan  43762176 Apr  4 00:45 packagesite.tar
-rw-r--r--  1 dan  dan  43758162 Apr  4 00:44 packagesite.yaml
-rw-r--r--  1 dan  dan       451 Jan  1  1970 packagesite.yaml.pub
-rw-r--r--  1 dan  dan       256 Jan  1  1970 packagesite.yaml.sig

**Comment by debdrup** [comment]
> Things to know:
> 
>     * How do we know what archs are available?
> 
>     * How do we know what versions?
As you've discovered, $ABI is a tuple consisting of FreeBSD:13:aarch64,  indicating both the major version and architecture.

**Comment by dlangille** [comment]
From there, we have this first line, as converted at https://jsonformatter.org/yaml-formatter

```
name: py37-pyasn1-modules
origin: devel/py-pyasn1-modules
version: 0.2.7
comment: 'Collection of ASN.1 data structures for py-pyasn1'
maintainer: rm@FreeBSD.org
www: 'https://github.com/etingof/pyasn1-modules'
abi: 'FreeBSD:12:*'
arch: 'freebsd:12:*'
prefix: /usr/local
sum: a8e5683326ffec8ee7ac645503484293fd6bbf3ccfc8df1ff14e6cd30d1d2707
flatsize: 1471522
path: All/py37-pyasn1-modules-0.2.7.txz
repopath: All/py37-pyasn1-modules-0.2.7.txz
licenselogic: single
licenses:
    - BSD2CLAUSE
pkgsize: 165056
desc: "This is a small but growing collection of ASN.1 data structures expressed in\nPython terms using pyasn1 data model.\n\nWWW: https://github.com/etingof/pyasn1-modules"
deps:
    py37-pyasn1:
        origin: devel/py-pyasn1
        version: 0.4.7
    py37-setuptools:
        origin: devel/py-setuptools
        version: 44.0.0
    python37:
        origin: lang/python37
        version: 3.7.7
categories:
    - devel
    - python
options:
    DOCS: on
annotations:
    flavor: py37
```

From that we have:

- origin `devel/py-pyasn1-modules`
- version `0.2.7`
-  name `py37-pyasn1-modules`

First idea, that can be tosses into a table just for package information. When displaying the page, a small table could be listed showing what is available for what, and as of what date/time.
