### ISSUE TITLE
Page for python37 doesn't include UPDATING entry 20191216

### ISSUE THREAD

**Issue by scotia70** [FreshPorts/freshports#155]
Likely because the line
```
AFFECTS: users of python
```
doesn't include lang/

**Comment by dlangille** [comment]
This, to me, is a bug with the UPDATING entry.

**Comment by dlangille** [comment]
From https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/moved-and-updating-files.html

If upgrading the port requires special steps like changing configuration files or running a specific program, it must be documented in this file. The format of an entry in this file is:

```
YYYYMMDD:
  AFFECTS: users of portcategory/portname
  AUTHOR: Your name <Your email address>

  Special instructions
```
